version: '3.7'

services:
  jaeger:
    image: jaegertracing/all-in-one:1.42
    ports:
      - "5775:5775"        # UDP trace receiver
      - "6831:6831/udp"    # UDP collector
      - "6832:6832/udp"    # Another UDP collector
      - "5778:5778"        # Zipkin-compatible endpoint
      - "14268:14268"      # HTTP collector
      - "14250:14250"      # gRPC collector
      - "16686:16686"      # Jaeger UI
      - "14259:14259"      # Trace validation
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411

