global:
  scrape_interval: 5s  # Default scrape interval

scrape_configs:
  - job_name: 'spring-boot-app'
    static_configs:
      - targets: ['spring-boot-app:8080']  # Adjust to match your service name and port
